# Generated by Django 5.2 on 2025-06-07 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_duration_of_stay', models.CharField(blank=True, help_text="e.g., '6 months', '1 year'", max_length=50, null=True)),
                ('full_name_on_form', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email_on_form', models.EmailField(blank=True, max_length=100, null=True)),
                ('current_address_on_form', models.TextField(blank=True, null=True)),
                ('university_name_on_form', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('spots_booked', models.IntegerField(default=1, help_text='Number of spots/rooms the user wants to book.')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.property')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
            },
        ),
    ]
