# Generated by Django 5.2 on 2025-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('owner', 'Owner'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
