# Generated by Django 5.2 on 2025-06-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('landlord', 'Landlord'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
