# Generated by Django 5.2 on 2025-06-14 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='receiver_of_payment',
            field=models.ForeignKey(blank=True, help_text='The user who is the ultimate recipient of this payment (e.g., Landlord).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
