# Generated by Django 5.2 on 2025-06-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='landlord',
            new_name='tenant',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('owner', 'Owner'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
