# Generated by Django 5.2 on 2025-06-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_paymentrecord_receiver_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
