# Generated by Django 5.2 on 2025-06-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='gender_preferred',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='any', help_text='Preferred gender for tenants for this property.', max_length=20),
        ),
    ]
